server:
  port: 8089
  
spring:
  application:
    name: DEPARTMENT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      
